export default{
    "occupations": [
      {
        "id": 1,
        "name": "css",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/ddd8f520-6189-4116-8822-68044f4fb01b.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "WEB工程师的必备技能，唯一零门槛入门的技术职业。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"5-10\"},{\"time\":\"1-3年\",\"salary\":\"10-20\"}]",
        "difficult": 1,
        "threshold": 1,
        "cycle": "2年",
        "company": 25744,
        "basis": "无门槛",
        "type": "front",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 3,
        "classCount": 143,
        "onlineClassCount": 365,
        "offlineClassCount": 22,
        "onlineUserCount": 7281,
        "offlineUserCount": 310,
        "coreUserCount": 8,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"产品设计好原型，UI做出来了效果图，剩下的就是CSS工程师用代码把静态页面写出来。\"},{\"name\":\"需要技能\",\"content\":\"环境【IDE(WEBStorm，Sublime，EditPlus)】\\n源码管理【(SVN/Git) ，WEB服务器(nginx)】\\n基础【PS，域名，Html，Html5，CSS，CSS3】\\n扩展【自适应，响应式，Bootstrap，Less，Flex】\"},{\"name\":\"发展前景\",\"content\":\"CSS工程师-初级JS工程师-JS工程师-前端架构师-前端Leader（IOS，Android和JS通吃）\\nCSS的发展前景最近几年好的不行。在Android和IOS大行其道的时候，一大部分人都转去做了这两个行业，然而突然之间，因为微信的缘故加上JS的魅力，H5突然又火爆起来，所以，CSS整体来说还是一个挺靠谱的职业。最关键的是，CSS是入门最快的职业，几乎零门槛，只是转JS还是挺不容易的。\"},{\"name\":\"入门门槛\",\"content\":\"无门槛\"},{\"name\":\"谁更合适\",\"content\":\"IT界：All\\n\\n其他界：All\"},{\"name\":\"职业限制\",\"content\":\"CSS的职业限制有三个：1、不去学自适应和响应式；2、不去学框架；3、学不会JS。这三点都是很重要的突破。css这个职业，在一家公司里可替代的程度比较高，并不算特别重要，做不了核心岗，也不存在什么代码交接。你就算代码写的再烂，也最多就是花一个月时间重写。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"环境配置或使用工具出现的问题简述。\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"图片\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"文本\",\"content\":{\"codeOrtext\":\"输入你想说的\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"你的源代码链接\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"detail\":\"环境配置或使用工具出现的问题简述。\",\"expLink\":\"http://kenghu.jnshu.com/k/question/163\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"编写代码或涉及方案时出现的问题简述。\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"代码\",\"content\":{\"codeOrtext\":\"输入代码\",\"imgOrSource\":\"对代码进行描述\"},\"type\":\"3\",\"isRequired\":\"0\"}],\"detail\":\"编写代码或涉及方案时出现的问题简述。\",\"expLink\":\"http://kenghu.jnshu.com/k/question/161\"}}",
        "createBy": "",
        "updateBy": 380,
        "updateAt": 1542050931966,
        "createAt": 7
      },
      {
        "id": 2,
        "name": "js",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/5a32d2c0-7b5b-403f-863b-4446f7235521.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "最疯狂的低门槛高薪水职业，从前端到后台无所不能。js目前是由css和js两个课程体系构成，一定要先学css课程，再学js。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"3-6\"},{\"time\":\"1-3年\",\"salary\":\"6-12\"},{\"time\":\"3年以上\",\"salary\":\"12-40\"}]",
        "difficult": 3,
        "threshold": 1,
        "cycle": "5年",
        "company": 12980,
        "basis": "要么是会了CSS，要么是精通了一种后端语言，千万不要CSS没学好，后端语言也不会就直接学JS，心里会没底，不踏实。",
        "type": "front",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 3,
        "classCount": 44,
        "onlineClassCount": 84,
        "offlineClassCount": 22,
        "onlineUserCount": 1681,
        "offlineUserCount": 333,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"A、对于套页面来说，JS工程师的职责非常简单，一个是做一些简单的动画和交互和验证，轮播图，弹框，验证用户名是否为空等等。\\n\\nB、另一个就是通过Ajax取一些后台数据，然后在页面上展示出来。那个时候的JS工程师并不被太多人重视，很多时候一些后端的人把前端的工作也做了。除了写CSS，大部分的后端工程师写点JS还是不成问题的。可是前后端分离的出现，彻彻底底的改变了前端的世界。前端居然有架构了，前端居然也有“编译”的概念了（你能想象么，JS的项目居然不能直接打开源码直接使用了，必须要经过编译才可以）。前端工程师和后端工程师只通过Json数据交互（感谢Nginx提供了一个完美的跨域解决方案，再也不用什么Jsonp了），然后服务器端的同学发现：好简单啊，我对Android，对IOS，对Html都只需要提供一套API就够了。\"},{\"name\":\"需要技能\",\"content\":\"环境【IDE（WEBStorm，Sublime，EditPlus），源码管理（SVN/Git） ，WEB服务器(nginx)】\\n\\n基础【Http，REST，跨域，语法，组件，F12，Json，Websocket】\\n\\n框架【JQuery，AngularJS，Bower，RequireJS，GruntJS，ReactJS，PhoneGap】\\n\\n业务【金融，教育，医疗，汽车，房产等等等等各种行业】\\n\\n第三方【微信，QQ等各种第三方登录，支付，IM，地图，语音，视频，图片】\"},{\"name\":\"发展前景\",\"content\":\"JS菜鸟-JS初级工程师-JS中级工程师-JS架构师-UED-前端Leader-前端大牛\\n\\nJS工程师在后面有一点后续无力，一般来说，还是强烈推荐JS，IOS，Android三者通吃.。这三者有太多相似之处了，到最后你会发现，语言只是一种工具而已。要做的事情，其实是差不太多的，并不需要对所有的语言都特别熟悉。\"},{\"name\":\"入门门槛\",\"content\":\"要么是会了CSS，要么是精通了一种后端语言，千万不要CSS没学好，后端语言也不会就直接学JS，心里会没底，不踏实。\"},{\"name\":\"谁更合适\",\"content\":\"IT界:CSS and All\\n\\n其他界:All\"},{\"name\":\"职业限制\",\"content\":\"JS的职业限制主要就在于学习的方向上很容易误入歧途。比如说一直坚持喜欢用原生，各种喜欢写一些奇怪语法，各种回调等等等等。学到一些好的框架其实很赞的，对于大多数人来讲，就够了。只是缺少一个清晰的指引。有的时候你会发现，你对Http了解的比较少，会是一个瓶颈。你对数组啊，循环啊不了解，是一个瓶颈。你对MVC不了解，也是另一个瓶颈。对Json不懂，不知道怎么定接口，也是个问题。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"环境配置或使用工具出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"图片\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"文本\",\"content\":{\"codeOrtext\":\"对问题进行描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"你的代码链接地址 （选填）\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"expLink\":\"http://kenghu.jnshu.com/k/question/163\",\"detail\":\"环境配置或使用工具出现的问题简述\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"编写代码或涉及方案时出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"代码\",\"content\":{\"codeOrtext\":\"输入代码\",\"imgOrSource\":\"对代码进行描述\"},\"type\":\"3\",\"isRequired\":\"0\"}],\"detail\":\"编写代码或涉及方案时出现的问题简述\",\"expLink\":\"http://kenghu.jnshu.com/k/question/166\"}}",
        "createBy": "",
        "updateBy": 388,
        "updateAt": 1542030783023,
        "createAt": 6
      },
      {
        "id": 3,
        "name": "Android",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/e6382b97-eb73-4a64-87fe-37337d391b16.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "这个世界上最流行的手机操作系统，Android大显神威。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"5-8\"},{\"time\":\"1-3年\",\"salary\":\"8-18\"},{\"time\":\"3年以上\",\"salary\":\"18-35\"}]",
        "difficult": 3,
        "threshold": 3,
        "cycle": "1年",
        "company": 16707,
        "basis": "java基础",
        "type": "front",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 24,
        "onlineClassCount": 37,
        "offlineClassCount": 3,
        "onlineUserCount": 731,
        "offlineUserCount": 11,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"Android工程师的日常就是听产品经理讲需求，跟后端定接口，听QA反馈哪款机器不兼容，闹着申请各种测试机，以及用Android做IOS的控件。\\nAndroid其实是对地图，支付，IM，第三方登录，短信，统计，音视频，文件，照片等等要求比较多的。业务上其实一般并不会有太多的内容。也很少会要求一些动画效果。再加一些手势密码。\"},{\"name\":\"需要技能\",\"content\":\"环境【Android Studio，Maven,Gradle】\\n基础【数据结构，Java，计算机网络】\\n扩展组件【IM，地图，支付，拍照，视频，音频，统计，分享，手势密码】\\n必备工具【java SDK，Android studio，Photoshop，svn，mark man，cutterman，post man，Fiddler，genymotion】\"},{\"name\":\"发展前景\",\"content\":\"Android工程师->Android Leader-》前端Leader\\n很少有Android工程师能够做到技术总监的。所以还是早做准备，Android，IOS和JS通吃。\"},{\"name\":\"入门门槛\",\"content\":\"门槛比较低了。比JS稍稍高一点儿，但也差别不大。主要是因为Android是纯客户端，要做就必须什么都懂。但是JS就不太一样了，有的时候要求不高也能做事儿。这就是Android比JS的门槛高一点的原因。简单来讲的话，最好是懂Java语法，然后是懂Http请求的含义，然后懂点儿MVC的概念，就可以了\"},{\"name\":\"谁更合适\",\"content\":\"IT界面:All\\n其他界:All(具备计算机基础)\"},{\"name\":\"职业限制\",\"content\":\"只掌握Android很难做到技术高层，应向其他技术进行扩展\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"环境配置或使用工具出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"图片\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"文本\",\"content\":{\"codeOrtext\":\"对问题进行描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"你的代码链接地址 （选填）\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"expLink\":\"http://dev.kenghu.skill.jnshu.com/k/question/4\",\"detail\":\"环境配置或使用工具出现的问题简述\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"编写代码或涉及方案时出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"代码\",\"content\":{\"codeOrtext\":\"输入代码\",\"imgOrSource\":\"对代码进行描述\"},\"type\":\"3\",\"isRequired\":\"0\"}],\"detail\":\"编写代码或涉及方案时出现的问题简述\",\"expLink\":\"http://dev.kenghu.skill.jnshu.com/k/question/4\"}}",
        "createBy": "",
        "updateBy": 380,
        "updateAt": 1541915714073,
        "createAt": 5
      },
      {
        "id": 4,
        "name": "iOS",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/d4234c89-5a7e-4339-80c7-505e0a435190.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "最近几年互联网前端开发的新贵，高冷职业的代表。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"6-8\"},{\"time\":\"1-3年\",\"salary\":\"8-18\"},{\"time\":\"3年以上\",\"salary\":\"18-35\"}]",
        "difficult": 3,
        "threshold": 3,
        "cycle": "1年",
        "company": 6600,
        "basis": "计算机基础",
        "type": "front",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 9,
        "onlineClassCount": 11,
        "offlineClassCount": 1,
        "onlineUserCount": 218,
        "offlineUserCount": 5,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"1.负责ios平台项目研发\\n2.完成iOS开发、Code Review、测试、bug修复、性能优化\\n3.编写产品设计文档、功能说明书等相关技术文档。\"},{\"name\":\"需要技能\",\"content\":\"1.熟练掌握Object-C/C,了解C++,对Object-C的内存管理机制有较好的理解;\\n2.熟练掌握MVC、单例、观察者、代理、工厂等设计模式以及NSNotificationCenter消息机制;\\n3.熟练掌握JSON/XML解析和GET/POST数据请求等操作\\n4.熟练使用AFNetworking、MBProgressHUD、SDWebImage等第三方框架;\\n5.熟练使用基于代码的应用程序框架搭建，熟悉xib和StoryBoard；\\n6.熟练掌握环信、支付、分享、定位等常用的第三方;\\n7.熟悉使用NSTread、GCD、NSOperation多线程开发;\\n8.熟练使用SVN代码管理工具\"},{\"name\":\"发展前景\",\"content\":\"IOS工程师->IOS Leader->前端Leader\"},{\"name\":\"入门门槛\",\"content\":\"1.具有扎实的计算机基础\\n2.计算机专业最好\"},{\"name\":\"谁更合适\",\"content\":\"IT界：都可以。哪怕你是产品，运维或者是QA\\n其他界：All(具备计算机基础)\"},{\"name\":\"职业限制\",\"content\":\"只掌握iOS很难做到技术高层，应向其他技术进行扩展\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"环境配置或使用工具出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"图片\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"文本\",\"content\":{\"codeOrtext\":\"对问题进行描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"你的代码链接地址 （选填）\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"expLink\":\"http://kenghu.skill.jnshu.com/k/question/163\",\"detail\":\"环境配置或使用工具出现的问题简述\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"编写代码或涉及方案时出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"代码\",\"content\":{\"codeOrtext\":\"输入代码\",\"imgOrSource\":\"对代码进行描述\"},\"type\":\"3\",\"isRequired\":\"0\"}],\"detail\":\"编写代码或涉及方案时出现的问题简述\",\"expLink\":\"http://kenghu.skill.jnshu.com/k/question/208\"}}",
        "createBy": "",
        "updateBy": 380,
        "updateAt": 1541738455720,
        "createAt": 4
      },
      {
        "id": 5,
        "name": "java",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/2bced196-dab7-4280-a655-fbe9f2211401.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "IT界的亲儿子，从出世到现在一直坚挺的中坚职业。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"6-8\"},{\"time\":\"2-5年\",\"salary\":\"8-18\"},{\"time\":\"5年以上\",\"salary\":\"20-50\"}]",
        "difficult": 5,
        "threshold": 5,
        "cycle": "7年",
        "company": 21207,
        "basis": "计算机基础(计算机网络，数据结构，数据库，操作系统，Java基础语法)。",
        "type": "backend",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 2,
        "classCount": 64,
        "onlineClassCount": 268,
        "offlineClassCount": 17,
        "onlineUserCount": 5347,
        "offlineUserCount": 196,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"拿到产品需求-》后端程序员做接口设计，架构设计，DB设计-》拿出方案来做技术方案评审-》评审通过，开始预估时间-》每日更新自己的Task-》接口完成自测一百遍，每日部署到开发环境，随时集成-》CodeReview-》重构代码-》性能测试-》Demo通过-》发布到测试环境-》修正Bug-》重新发布-》发布到线上环境。\"},{\"name\":\"需要技能\",\"content\":\"环境【IDE（Idea/Eclipse，Maven，jenkins，Nexus，Jetty，Shell，Host)、源码管理(SVN/Git)，WEB服务器(nginx,tomcat,Resin)】\\n\\n基础【Http，REST，跨域，语法，Websocket,数据库，计算机网络，操作系统，算法，数据结构】\\n\\n框架【Spring，AOP，Quartz，Json TagLib,tiles,activeMQ,memcache,redis,mybatis,log4j,junit】\\n\\n框架【业务【金融，教育，医疗，汽车，房产等各种行业】】\\n\\n第三方【微信、QQ等各种第三方登录、支付、IM、地图、语音、视频、图片】\"},{\"name\":\"发展前景\",\"content\":\"Java初级工程师-Java中级工程师-架构师-技术经理-技术总监-CTO-CEO\\n\\n后端的爆发力并不差，只要你给他时间，只要你愿意前进，后端的路线很深，深到你有时候会觉得自己还没来得及全部了解，就已经有无数的新人涌进来要替换你的位置了。\"},{\"name\":\"入门门槛\",\"content\":\"计算机基础(计算机网络，数据结构，数据库，操作系统，Java基础语法)。\"},{\"name\":\"谁更合适\",\"content\":\"IT界:无\\n\\n其他界:无\\n\\n科班生:计算机专业的中等水平能力以上\"},{\"name\":\"职业限制\",\"content\":\"职业限制就是不去做独立的项目，不做DB设计，不做接口设计。第二个职业限制就是视野不开阔，不知道有什么样的开源软件可以用。第三个职业限制就是不重视线上环境，不知道如何写日报，也不知道如何快速定位。我不得不说我带过的兄弟，有一次解决线上问题的时候快把我气疯了，他们在那里猜测问题出现的原因，跟玩福尔摩斯一样，不打日志不看日志，根据现象倒推结果，直接盲改代码再扔到线上看看有没有解决问题---那是最后逼不得已的办法好么，在此之前能不能安静的把日志打出来，确认一下到底是哪里出错了？第四个职业限制就是不懂版本管理，不懂Bug修复流程，不懂开发流程。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量把问题表述清楚，如出现问题的具体操作步骤，以及展示的异常结果等\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"错误截图\",\"content\":{\"imgOrSource\":\"对图片进行描述\"},\"type\":\"2\",\"isRequired\":\"1\"}],\"detail\":\"请尽量把问题表述清楚，如出现问题的具体操作步骤，以及展示的异常结果等\",\"expLink\":\"http://kenghu.jnshu.com/k/question/163\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量把问题表述清楚，如环境配置、SDK版本、异常堆栈信息等，最好能附上代码\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"错误截图\",\"content\":{\"imgOrSource\":\"对图片进行描述\"},\"type\":\"2\",\"isRequired\":\"1\"},{\"name\":\"源码\",\"content\":{\"codeOrtext\":\"异常部分代码\",\"imgOrSource\":\"异常日志信息\"},\"type\":\"3\",\"isRequired\":\"1\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"可提供源码链接\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"detail\":\"请尽量把问题表述清楚，如环境配置、SDK版本、异常堆栈信息等，最好能附上代码\",\"expLink\":\"http://kenghu.jnshu.com/k/question/186\"}}",
        "createBy": "",
        "updateBy": 380,
        "updateAt": 1542039641364,
        "createAt": 3
      },
      {
        "id": 6,
        "name": "op",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/3f0e7533-da28-47ab-b119-9eb6e9d0646c.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "越来越重要的岗位，“云服务和安全”必备职业。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"6-8\"},{\"time\":\"1-3年\",\"salary\":\"8-18\"}]",
        "difficult": 1,
        "threshold": 2,
        "cycle": "2年",
        "company": 25744,
        "basis": "OP的门槛其实并没有太高，经常玩玩Linux会好一些，但是要学的东西，确实挺多的。处理线上故障，也是一个经验积累的过程，所以说呢，基本上算是0门槛，谁都可以考虑做，只是要看你喜欢，或者是不喜欢，进度快和慢的问题而已。",
        "type": "op",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 16,
        "onlineClassCount": 20,
        "offlineClassCount": 5,
        "onlineUserCount": 393,
        "offlineUserCount": 6,
        "coreUserCount": 2,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"A、基础环境的搭建和常用软件的安装和配置（兼网管的还有各种程控机）,常用软件指的是SVN，Git，邮箱这种，更细节的内容请参考修真院对于运维职业的介绍。\\n\\nB、日常的发布和维护，如刚刚讲到的一样，测试环境和线上环境的发布和记录，原则上，对线上所有的变更都应该有记录。\\n\\nC、数据的备份和服务的监控&安全配置。各种数据，都要做好备份和回滚的手段，提前准备好各种紧急预案，服务的监制要做好。安全始终都是不怎么被重点考虑的问题，因为这个东西无底洞，你永远不知道做到什么程度算是比较安全了，所以大多数都是看着情况来\\n\\nD、运维工具的编写。这一点在大的云服务器商里格外常见，大公司也是一样的\\n\\nE、Hadoop相关的大数据体系架构的运维。\"},{\"name\":\"需要技能\",\"content\":\"环境【Linux，Mysql，Oracle，MongoDB，Hadoop，nginx,apache,F5,lvs,vpn,iptable，svn,git,memcache,redis】；工具【linux 常用工具，Mysql常用工具，Jenkins，zabbix,nagios】；自动化运维【openstack,docker,ansible】；语言【shell,python】\"},{\"name\":\"发展前景\",\"content\":\"网管-初级运维工程师-中级运维工程师-高级运维工程师；运维做到高级运维工程师这个级别，已经到头了。很少有运维的同事能做到技术叫监的级别的。所以，对于资质一般的你来说，选择了做运维，就代表着天花板很近，但是对于大多数人来说，已经可以了\"},{\"name\":\"入门门槛\",\"content\":\"OP的门槛其实并没有太高，经常玩玩Linux会好一些，但是要学的东西，确实挺多的。处理线上故障，也是一个经验积累的过程，所以说呢，基本上算是0门槛，谁都可以考虑做，只是要看你喜欢，或者是不喜欢，进度快和慢的问题而已。\"},{\"name\":\"谁更合适\",\"content\":\"IT界：后端工程师，网管；其他界：All\"},{\"name\":\"职业限制\",\"content\":\"这样责任和权利分开。所以运维工程师能够相对有更多的时间去研究技术，然而坏处就是对一个行业了解的会比较少。所以这个职业比较大的问题就是，想要再转行成其他的职业，已经很难了，只能一条路走到黑。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"环境配置或使用工具出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"图片\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"文本\",\"content\":{\"codeOrtext\":\"对问题进行描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"你的代码链接地址 （选填）\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"expLink\":\"http://dev.kenghu.skill.jnshu.com/k/question/4\",\"detail\":\"环境配置或使用工具出现的问题简述\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"编写代码或涉及方案时出现的问题简述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"对截图进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"代码\",\"content\":{\"codeOrtext\":\"输入代码\",\"imgOrSource\":\"对代码进行描述\"},\"type\":\"3\",\"isRequired\":\"0\"}],\"detail\":\"编写代码或涉及方案时出现的问题简述\",\"expLink\":\"http://dev.kenghu.skill.jnshu.com/k/question/4\"}}",
        "createBy": "",
        "updateBy": 380,
        "updateAt": 1541698265459,
        "createAt": 2
      },
      {
        "id": 7,
        "name": "pm",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/63df88fe-aff7-4136-9429-f720bc92aac5.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "入门门槛虽低，却是成为CEO的最佳职位",
        "salary": "[{\"time\":\"0-2年\",\"salary\":\"6-15\"},{\"time\":\"2-4年\",\"salary\":\"12-25\"},{\"time\":\"4年以上\",\"salary\":\"20-50\"}]",
        "difficult": 3,
        "threshold": 1,
        "cycle": "5年",
        "company": 23614,
        "basis": "无（甚至你可以不认识字)",
        "type": "ued",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 3,
        "classCount": 36,
        "onlineClassCount": 80,
        "offlineClassCount": 11,
        "onlineUserCount": 1582,
        "offlineUserCount": 98,
        "coreUserCount": 1,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"了解用户需求、做竞品调研、画产品原型、写产品文档、讲解产品需求、测试产品Bug、收集用户反馈\"},{\"name\":\"需要技能\",\"content\":\"PPT，Word, Axure,XP,MVP，行业知识，沟通\"},{\"name\":\"发展前景\",\"content\":\"产品助理-产品经理-高级产品经理-产品总监-CEO\\n\\n不用说，产品经理绝对是一个炙手可热的职业，而且，TNND的几乎是零门槛，这表示，是个人都可以说，我想成为一个产品经理。 然而，好的产品经理很多么？并不多，所以，好像围棋一样的，入门容易，学精难。 而且，似乎并没有一个系统的教程（这真是一个很难让人相信的事情啊，这么一种职业，没有大学的知识培养，甚至都很少有标准化的职业化培训，全靠业界手把手培养和自发的交流，就能够拿着无数DS程序员根本就想像不到的薪水--产品经理真的跟DS有点儿不搭边的，当然，我大修真还是在努力做产品人员的培养的）。 产品经理的发展前景是很赞的，只是越来越体系化了，而且很容易出人头地。\"},{\"name\":\"入门门槛\",\"content\":\"无（甚至你可以不认识字)\"},{\"name\":\"谁更合适\",\"content\":\"IT界：程序员，UI，QA，运营，市场\\n\\n其他界：无限制\"},{\"name\":\"职业限制\",\"content\":\"很多产品经理都很怕跟程序员沟通。而且经常会苦恼，觉得自己设计的功能，程序员做不了，做不出来，做的太慢，做的太差。惟独不会觉得自己设计的太烂。 所以，很多产品经理都会认为不通技术是自己的一个弱项，我曾经整理过一个产品经理需要了解的技术术语，有需要直接去任务里找。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量详细的描述问题\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"如有必要，可对问题截图进行说明解释\"},\"type\":\"2\",\"isRequired\":\"1\"}],\"detail\":\"请尽量详细的描述问题\",\"expLink\":\"http://kenghu.jnshu.com/k/question/146\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量详细的描述问题\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"问题截图\",\"content\":{\"imgOrSource\":\"请对问题截图进行说明解释\"},\"type\":\"2\",\"isRequired\":\"1\"},{\"name\":\"源文件\",\"content\":{\"codeOrtext\":\"可上传至云盘后将地址分享至此，密码备注于描述中即可\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"detail\":\"请尽量详细的描述问题\",\"expLink\":\"http://kenghu.jnshu.com/k/question/182\"}}",
        "createBy": "",
        "updateBy": 376,
        "updateAt": 1542005534940,
        "createAt": 1
      },
      {
        "id": 8,
        "name": "ui",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/72c5ce23-f0b0-48f0-a867-264a3175e4f4.png",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "最近几年互联网前端开发的新贵，高冷职业的代表。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"6-8\"},{\"time\":\"1-3年\",\"salary\":\"8-18\"},{\"time\":\"3年以上\",\"salary\":\"18-35\"}]",
        "difficult": 3,
        "threshold": 3,
        "cycle": "1年",
        "company": 6600,
        "basis": "UI对入门门槛要求还算是比较高的。首先你得有一台Mac。。大部分的情况下你都需要Mac。然后你要懂之前提到的常用软件，UI的交互规范，配色等等等。。",
        "type": "ued",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 12,
        "onlineClassCount": 29,
        "offlineClassCount": 7,
        "onlineUserCount": 578,
        "offlineUserCount": 30,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"UI表面上看是用户与界面两个组成部分，但实际上还包括用户与界面之间的交互关系。具体还包括：可用性分析、GUI（Graphic User Interface即图形用户界面）设计、用户测试等。好的UI设计不只是让软件变得有个性有品味而已，更重要的是让软件的操作变得舒适、简单、易用，并且充分体现软件的定位和特点。\"},{\"name\":\"需要技能\",\"content\":\"PS，Illustrator，Sketch，耐性，找素材\"},{\"name\":\"发展前景\",\"content\":\"实习UI-初级U-中级UI-高级UI（UE)\"},{\"name\":\"入门门槛\",\"content\":\"UI对入门门槛要求还算是比较高的。首先你得有一台Mac。。大部分的情况下你都需要Mac。然后你要懂之前提到的常用软件，UI的交互规范，配色等等等。。\"},{\"name\":\"谁更合适\",\"content\":\"IT界：无\\n\\n其他界：传统做VI的，就是平面设计的会转一些。跟着基本上就是小鲜肉了，刚毕业就从事这个行业的会比较多一些。还有一些学美术的，会手绘的。\"},{\"name\":\"职业限制\",\"content\":\"UI这个职业的限制在某种程度上就是不太清楚自己应该朝着UE发展。所以时间长了工作就会变得单调，两年或者是三年之后原地踏步走没怎么有进步的人很多。像Metro（扁平化）或者是material design这样的风格一不熟悉二不了解三不想尝试的人还是挺多的。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量详细的描述问题\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"问题截图\",\"content\":{\"imgOrSource\":\"截图说明...\"},\"type\":\"2\",\"isRequired\":\"0\"}],\"detail\":\"请尽量详细的描述问题\",\"expLink\":\"http://kenghu.jnshu.com/k/question/142\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"问题截图\",\"content\":{\"imgOrSource\":\"截图说明...\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"源文件\",\"content\":{\"codeOrtext\":\"可将源文件上传至云盘，复制地址至此，密码可备注到详情描述中...\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"http://kenghu.jnshu.com/k/question/142\"}}",
        "createBy": "",
        "updateBy": 380,
        "updateAt": 1541666332000,
        "createAt": 0
      },
      {
        "id": 9,
        "name": "qa",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/01e1cf98-eea6-4d7f-8d0c-1397636ac247.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "项目的守护神。",
        "salary": "[{\"time\":\"0-2\",\"salary\":\"6--10\"},{\"time\":\"2--4年\",\"salary\":\"8--16\"},{\"time\":\"4年以上\",\"salary\":\"15--25\"}]",
        "difficult": 1,
        "threshold": 1,
        "cycle": "3年",
        "company": 32458,
        "basis": "无",
        "type": "ued",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 6,
        "onlineClassCount": 19,
        "offlineClassCount": 5,
        "onlineUserCount": 370,
        "offlineUserCount": 14,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"1.了解产品需求。2.对功能点进行分析。3.编写测试用例。4.执行测试用例。5.使用bug工具。6.追踪bug状态。\"},{\"name\":\"需要技能\",\"content\":\"excel、jmeter、loadrunner、行业知识、沟通、\"},{\"name\":\"发展前景\",\"content\":\"QA贯穿整个项目，它要保证产品的质量，所以被称为“项目的守护神”。\\n测试四大魅力:1.就业竞争小 2.高薪没商量 3.多元化发展\"},{\"name\":\"入门门槛\",\"content\":\"无\"},{\"name\":\"谁更合适\",\"content\":\"IT界：程序员、运营、市场、PM、UI、  其他界：无限制\"},{\"name\":\"职业限制\",\"content\":\"如果测试对产品需求业务逻辑不了解， 会导致在测试期间流程行不通。所以不要不敢怼产品，在需求评审时候都思维的进行思考，有问题提前提出来，避免对人力物力造成不必要的损失。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"截图\",\"content\":{\"imgOrSource\":\"截图说明...\"},\"type\":\"2\",\"isRequired\":\"1\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"http://kenghu.jnshu.com/k/question/160\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"解决方案\",\"content\":{\"codeOrtext\":\"请输入你的解决方案\"},\"isRequired\":\"1\",\"type\":\"1\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"http://kenghu.jnshu.com/k/question/165\"}}",
        "createBy": 101,
        "updateBy": 380,
        "updateAt": 1541809193173,
        "createAt": -1
      },
      {
        "id": 10,
        "name": "求职辅导",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/7eae7c16-0287-4e01-8aa8-a436a7fc8cd5.",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "这么久了还没有找到工作？需要简历和面试辅导吗。修真院老大亲自出马，一对一简历与面试辅导，助你成功入职！",
        "salary": "[{\"time\":\"1-2周\",\"salary\":\"2\"}]",
        "difficult": 1,
        "threshold": 1,
        "cycle": "1年",
        "company": "",
        "basis": "无",
        "type": "ued",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 0,
        "classCount": 1,
        "onlineClassCount": 1,
        "offlineClassCount": 0,
        "onlineUserCount": 8,
        "offlineUserCount": 0,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"入门门槛\",\"content\":\"无\"},{\"name\":\"谁更合适\",\"content\":\"即将踏上职场，准备求职或正在求职的人\"},{\"name\":\"职业限制\",\"content\":\"IT\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"https:www.baidu.com\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"https:www.baidu.com\"}}",
        "createBy": 101,
        "updateBy": 365,
        "updateAt": 1533978478482,
        "createAt": -2
      },
      {
        "id": 11,
        "name": "python",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/da2397b0-f7ff-4e85-8948-b6d6d34d7e1d.png",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "一种简单而又强大的语言，它合理地结合了高性能与使编写程序变得简单有趣的特色",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"5-8\"},{\"time\":\"1-3年\",\"salary\":\"8-15\"}]",
        "difficult": 3,
        "threshold": 2,
        "cycle": "1年",
        "company": 13852,
        "basis": "1、会使用电脑；2、还记得初中数学的一些方程式和代数知识；3、看懂一些基础的单词",
        "type": "backend",
        "publishAt": "",
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 2,
        "onlineClassCount": 32,
        "offlineClassCount": 1,
        "onlineUserCount": 626,
        "offlineUserCount": 2,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"从入门级到专业级选手都在做的：爬虫\\n还可以可以做日常任务，各种需要实现的小功能\\n可以做网站，比如知乎、YouThube、豆瓣就是Python写的\\n可以做网络游戏的后台，很多在线游戏的后台都是Python开发的\"},{\"name\":\"需要技能\",\"content\":\"Python元编程，通过一些优秀的开源代码来学习，比如sqlalchemy,gunicorn\\n了解常见的web框架，django,flask,tornado\\n然后对数据库也需要了解，比如SQL，Mongodb\\n后期就看你发展方向啦，是向数据分析、机器学习方面，还是做爬虫做web后端开发都可以\"},{\"name\":\"发展前景\",\"content\":\"前景一：Linux运维\\nLinux运维施必须而且一定要掌握Python语言，满足运维工程师的工作需求提升效率\\n\\n前景二：Python Web工程师\\nPython的框架可以做网站，而且都是一些精美的前端界面，还有一些数据的应用\\n\\n前景三：Python自动化测试\\n自动化测试中Python语言的用途很广，需要掌握和熟悉自动化流程、方法和各个模板\\n\\n前景四：数据分析\\nPython语言是数据分析师的第一首选，大数据时代给工作带来了很大的便利\"},{\"name\":\"入门门槛\",\"content\":\"了解基本的计算机知识，正常人的学习能力\"},{\"name\":\"谁更合适\",\"content\":\"IT届：All\\n其他届：All（具备计算机基础）\"},{\"name\":\"职业限制\",\"content\":\"职业限制很大程度上跟技术局限性有关\\n比如：\\n要写操作系统，这个只能C语言写\\n写手机应用，只能Objective-C和Java\\n写3D游戏，最好用C或C++\\n那么相关的岗位当然就受限了\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量把问题表述清楚，如出现问题的具体操作步骤，以及展示的异常结果等\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"错误截图\",\"content\":{\"codeOrtext\":\"对图片进行描述\",\"imgOrSource\":\"对图片进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"}],\"detail\":\"请尽量把问题表述清楚，如出现问题的具体操作步骤，以及展示的异常结果等\",\"expLink\":\"http://kenghu.jnshu.com/k/question/163\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请尽量把问题表述清楚，如环境配置、SDK版本、异常堆栈信息等，最好能附上代码\"},\"type\":\"1\",\"isRequired\":\"0\"},{\"name\":\"错误截图\",\"content\":{\"codeOrtext\":\"对图片进行描述\",\"imgOrSource\":\"对图片进行描述\"},\"type\":\"2\",\"isRequired\":\"0\"},{\"name\":\"源码\",\"content\":{\"codeOrtext\":\"异常部分代码\",\"imgOrSource\":\"异常日志信息\"},\"type\":\"3\",\"isRequired\":\"1\"},{\"name\":\"url\",\"content\":{\"codeOrtext\":\"可提供源码链接\"},\"type\":\"4\",\"isRequired\":\"1\"}],\"detail\":\"请尽量把问题表述清楚，如环境配置、SDK版本、异常堆栈信息等，最好能附上代码\",\"expLink\":\"请尽量把问题表述清楚，如环境配置、SDK版本、异常堆栈信息等，最好能附上代码\"}}",
        "createBy": 386,
        "updateBy": 365,
        "updateAt": 1541959263889,
        "createAt": 1502788061495
      },
      {
        "id": 12,
        "name": "运营",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/178817ba-78f8-484b-9a8e-f33ab3fc5b21.jpg",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "线上线下，好的运营让产品与用户形影不离。",
        "salary": "[{\"time\":\"0-1\",\"salary\":\"6-10\"},{\"time\":\"1-3\",\"salary\":\"8-20\"},{\"time\":\"3年以上\",\"salary\":\"20-50\"}]",
        "difficult": 3,
        "threshold": 1,
        "cycle": "3年",
        "company": 2648,
        "basis": "一点行业知识以及情商。",
        "type": "ued",
        "publishAt": 1514340750936,
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 4,
        "onlineClassCount": 5,
        "offlineClassCount": 3,
        "onlineUserCount": 86,
        "offlineUserCount": 4,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"1、找到用户在哪；2、以能接受的成本拉来用户，让他们用你的产品；3、让用户持续用你的产品，进行用户运营，社区运营；4、跟用户在不用产品时候保持联系。\"},{\"name\":\"需要技能\",\"content\":\"行业知识，人脉，文笔， 数据分析\"},{\"name\":\"发展前景\",\"content\":\"绝对好。无论技术发展到什么程度，无论产品变换多少次风格，运营的核心理念都不会变，积累的人脉不会变。运营，可以做100年。\"},{\"name\":\"入门门槛\",\"content\":\"这个说要门槛，有点谈不上。毕竟有深有浅，情商要高是必须的，其他的只能说有了更好。 好的吧，就算是情商低也可以去做编辑，每天只是对着后台系统一阵改。\"},{\"name\":\"谁更合适\",\"content\":\"IT界：程序员，UI，QA，PM，市场\\n其他界：无限制\"},{\"name\":\"职业限制\",\"content\":\"运营人员常常会受限于资源，也常常会迷失在数据里，很多运营的人，其实是做不到那么 高的职位的，对于他们来说，自己的行业积累和人脉积累没什么用处，因为只有你本身有价值，你才能跟别人互相交换。所以有的时候会高不成低不就，退回去做产品和技术，又缺少专业技能。这大概也是运营这个岗位的职业限制吧，缺少干货，心里容易没底气。\"}]",
        "questionModules": "{\"1\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"https:www.baidu.com\"},\"2\":{\"module\":[{\"name\":\"详细描述\",\"content\":{\"codeOrtext\":\"请输入问题详情描述\"},\"type\":\"1\",\"isRequired\":\"0\"}],\"detail\":\"请输入问题详情描述\",\"expLink\":\"https:www.baidu.com\"}}",
        "createBy": 377,
        "updateBy": 377,
        "updateAt": 1541405867736,
        "createAt": 1514340750966
      },
      {
        "id": 14,
        "name": "动画师",
        "img": "http://jns.img.bucket.ks3-cn-beijing.ksyun.com/skill/1/86bd36b9-fe44-4994-b662-ce0555c3600f.png",
        "brief": "无",
        "qq": "",
        "qqUrl": "",
        "description": "逐渐火热的传统职业，互联网甚至更多领域的新贵。",
        "salary": "[{\"time\":\"0-1年\",\"salary\":\"6-8\"},{\"time\":\"1-3年\",\"salary\":\"8-18\"},{\"time\":\"3年以上\",\"salary\":\"18-35\"}]",
        "difficult": 4,
        "threshold": 4,
        "cycle": "1年",
        "company": 5000,
        "basis": "动画师的门槛不算高，感谢Adobe系列软件在各系统的兼容性！但你要有对运动的敏感性和一双发现美的眼睛，然后需要学会除了动画制作软件AE外的大量相关软件和插件的使用，这是一个需要全面发展的职业。",
        "type": "ued",
        "publishAt": 1536377848311,
        "status": "",
        "onlineGradeCount": 1,
        "offlineGradeCount": 1,
        "classCount": 2,
        "onlineClassCount": 1,
        "offlineClassCount": 1,
        "onlineUserCount": 3,
        "offlineUserCount": 3,
        "coreUserCount": 0,
        "modules": "[{\"name\":\"工作内容\",\"content\":\"动画师从表面看只要制作动画就好，但实际上你还需要掌握相关的绘画技巧，视频的剪辑和后期制作，偶尔兼职加个字幕剪个音频什么的。好的动画师不仅能制作二维动画，同时也可以制作好的视频，需要一定的创造力，能够根据文案设计分镜，最终制作出流畅有趣的动画。\"},{\"name\":\"需要技能\",\"content\":\"AE PS AI 耐性 节奏感\"},{\"name\":\"发展前景\",\"content\":\"实习动画师-初级动画师-中级动画师-高级动画师\"},{\"name\":\"入门门槛\",\"content\":\"动画师的门槛不算高，感谢Adobe系列软件在各系统的兼容性！但你要有对运动的敏感性和一双发现美的眼睛，然后需要学会除了动画制作软件AE外的大量相关软件和插件的使用，这是一个需要全面发展的职业。\"},{\"name\":\"谁更合适\",\"content\":\"IT界：无 其他界：传统做VI的，就是平面设计的会转一些。跟着基本上就是小鲜肉了，刚毕业就从事这个行业的会比较多一些。还有一些学美术的，会手绘的。\"},{\"name\":\"职业限制\",\"content\":\"动画师这个职业的限制在某种程度上就是固守自己现在所做的动画类型。对影视、MG动画、二维动画、三维动画等动画类型没有过尝试。习惯于根据脚本制作动画，却不自己进行设计修改，很容易在两年或者是三年之后原地踏步没什么进步。\"}]",
        "questionModules": "",
        "createBy": 393,
        "updateBy": 386,
        "updateAt": 1541496333142,
        "createAt": 1536377848323
      }
    ]
 
}